language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t liu-lian/docker-react -f Dockerfile.dv .

script:
  - docker run -e CI=true liu-lian/docker-react npm run test
